name: CC Test Coverage
on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      # Node versions list
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
        env:
          CI: true
      - run: make install
      - run: make test
  coverage:
    needs: [test]
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: make install
      - uses: paambaati/codeclimate-action@v2.2.4
        env:
          CI: true
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npx jest --coverage
