# Name of workflow
name: Developer-CI

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      # Node versions list
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Developer CI
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run npm install
        run: |
          make install
        env:
          CI: true
      - name: Run linter
        run: |
          make lint
      - name: Run tests
        run: |
          make test
